### ISSUE TITLE
Wiki Updates

### ISSUE THREAD

**Issue by noah-hart** [StealthSend/Stealth#15]
- Update https://github.com/StealthSend/Stealth/wiki adding
> Note: Ubuntu client builds require at least 3GB memory
> Daemon Deployment on Ubuntu 19.10 & 20.04

- rename https://github.com/StealthSend/Stealth/wiki/Daemon-Client-Deployment-on-Ubuntu-19.10 to 19.10 & 20.04
or create 20.04 deployment page (instructions are identical to 19.10

TIA -- NH

**Comment by StealthSend** [comment]
Good point about 20.04. The page should be added. The odd version numbers of Ubuntu are typically for development releases, and "placeholders" for the even version numbers, meaning Ubuntu 19 instructions should be applicable for Ubuntu 20, but that's not common knowledge.

On the memory, all the build pages already say that 3 GB is needed as of 10/2020. That edit was added at that time.
